# Generated by Django 2.0.4 on 2018-04-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('display', models.PositiveIntegerField(default=0)),
                ('wasted', models.PositiveIntegerField(default=0)),
                ('limit', models.PositiveIntegerField(default=10)),
                ('isWarning', models.BooleanField(default=False)),
                ('isTimerRunning', models.BooleanField(default=False)),
            ],
        ),
    ]
