# Generated by Django 2.0.4 on 2018-04-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180406_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcounter',
            old_name='display_item',
            new_name='displayed_item',
        ),
        migrations.RenameField(
            model_name='productcounter',
            old_name='waste_item',
            new_name='wasted_item',
        ),
    ]
