# Generated by Django 2.0.4 on 2018-04-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180407_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcounter',
            old_name='product',
            new_name='product_id',
        ),
    ]
