# Generated by Django 2.0.4 on 2018-04-09 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180409_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='wasted_time',
            new_name='wasted_item',
        ),
    ]
