# Generated by Django 2.0.4 on 2018-04-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
