# Generated by Django 2.0.4 on 2018-04-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20180409_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='left_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
