# Generated by Django 2.0.4 on 2018-04-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20180410_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcounter',
            old_name='product_id',
            new_name='product',
        ),
    ]
