# Generated by Django 2.0.4 on 2018-04-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20180410_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcounter',
            name='product',
        ),
        migrations.AddField(
            model_name='productcounter',
            name='product_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
