# Generated by Django 2.0.4 on 2018-04-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20180410_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcounter',
            old_name='product_id',
            new_name='product_ku',
        ),
    ]
