# Generated by Django 2.0.4 on 2018-04-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20180410_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcounter',
            name='product_ku',
        ),
        migrations.AddField(
            model_name='productcounter',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product'),
        ),
    ]
