# Generated by Django 2.0.4 on 2018-04-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20180411_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcounter',
            name='sold_item',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
