# Generated by Django 2.0.4 on 2018-04-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20180411_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_file',
        ),
    ]
