# Generated by Django 2.0.4 on 2018-04-30 04:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_product_img_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcounter',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
