# Generated by Django 2.0.4 on 2018-04-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20180430_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='level',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
